version: "3"

services:
  nst:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/start-reload.sh"]
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
